### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by reid23** [rmn388/dog-treat-dispenser#1]
The cad for the piece of the box that holds the motion detector and the camera is not posted (or I can't find it).  can you tell me where it is or upload it if it is not yet?  thanks!

**Comment by Rich-Nelson** [comment]
Good catch,  I just added the files in the cad folder under the names Box Camera Mount.STL and Box Camera Mount.STEP

**Comment by Rich-Nelson** [comment]
Good catch, I just added the files to the CAD folder under the name Box Camera Mount.STL and Box Camera Mount.STEP
